import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { LazyMotion, domAnimation } from "framer-motion";
import Header from "@/components/Header";
import ActiveSectionContextProvider from "@/context/active-section-context";
import Footer from "@/components/Footer";


const poppins = Poppins({
  subsets: ["latin"], // Choose language subsets as needed
  weight: ["200", "300", "400", "500", "700"], // Include only the weights you use
  variable: "--font-poppins", // Optional CSS variable
  preload: true, // Ensures the font is preloaded automatically
});

export const metadata: Metadata = {
  title: "OrdinacijaCMS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="bs">
      <body
        className={`${poppins.variable} relative  antialiased flex flex-col min-h-screen`}
      >
        <LazyMotion features={domAnimation}>
          <ActiveSectionContextProvider>
          <Header />  
 
            <main className="flex-1 flex flex-col">{children}</main>
            <Footer />
          </ActiveSectionContextProvider>
        </LazyMotion>
      </body>
    </html>
  );
}
